---

- name: Template diun config
  ansible.builtin.template:
    src: diun.yml.j2
    dest: /etc/diun.yml
    owner: root
    group: root
    mode: '0644'

- name: Run diun container
  community.docker.docker_container:
    name: diun
    image: ghcr.io/crazy-max/diun
    command: "serve"
    state: started
    restart_policy: unless-stopped
    env:
      TZ: "Europe/London"
      LOG_LEVEL: "info"
      LOG_JSON: "false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ diun.datadir }}:/data"
      - "/etc/diun.yml:/diun.yml:ro"
