roles:
  - src: artis3n.tailscale
  - src: geerlingguy.docker
  - src: grog.package
  - src: ironicbadger.bash_aliases
  - src: bodsch.snapd
  - src: https://github.com/andornaut/ansible-role-rsnapshot
  - src: andrewrothstein.starship
collections:
  - name: community.docker
