---
- name: Create necessary directories
  become_user: "{{ user.username }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - $HOME/.local/bin
    - $HOME/.config/chezmoi

- name: install chezmoi
  become_user: "{{ user.username }}"
  ansible.builtin.shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
  args:
    creates: $HOME/.local/bin/chezmoi

- name: template chezmoi config
  become_user: "{{ user.username }}"
  ansible.builtin.template:
    src: dot-config_chezmoi_chezmoi.toml.j2
    dest: $HOME/.config/chezmoi/chezmoi.toml
    owner: "{{ user.username }}"
    group: "{{ user.group }}"
    mode: "0644"

- name: initialize and apply chezmoi dotfiles repository
  become_user: "{{ user.username }}"
  command:
    cmd: ./chezmoi init --apply {{ chezmoi_repo }}
    chdir: $HOME/.local/bin
    creates: $HOME/.local/share/chezmoi

- name: install vim-plug
  become_user: "{{ user.username }}"
  command:
    cmd: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    creates: $HOME/.vim/autoload/plug.vim

- name: install vim plugins
  tags: never
  become_user: "{{ user.username }}"
  command: vim +'PlugInstall --sync' +qa