- name: create main user
  tags: bootstrap
  user:
    name: "{{ user.username }}"
    groups:
      - root
    append: true

- name: add sudoers file for main user
  tags: bootstrap
  ansible.builtin.template:
    src: users/sudoer_user.j2
    dest: "/etc/sudoers.d/{{ user.username }}"
    owner: root
    group: root
    mode: 0440

- name: add ssh public key for main user
  tags: ssh, bootstrap
  authorized_key:
    user: "{{ user.username }}"
    key: "{{ item }}"
  loop: "{{ ssh_public_keys }}"

- name: Prevent SSH Password Authentication
  tags: ssh, bootstrap
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication\s'
    line: "PasswordAuthentication no"
    state: present
  notify:
    - restart sshd

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: start/enable services
  tags: systemd
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ systemd_services }}"
