---

- name: disks
  include_tasks:
    file: disks.yml
    apply:
      tags: disks
  tags:
    - disks

- name: snapraid
  include_tasks:
    file: snapraid.yml
    apply:
      tags: snapraid
  tags: snapraid

- name: samba
  include_tasks:
    file: samba.yml
    apply:
      tags: samba
  tags: samba

- name: firewall
  include_tasks:
    file: ufw_firewall.yml
    apply:
      tags: firewall
  tags: firewall

- name: mask sleep/suspend services
  tags: systemd
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Write SSH Public Key
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    dest: $HOME/.ssh/id_ed25519.pub
    mode: 0644
    content: "{{ ssh_public_key }}"

- name: Write SSH Private Key
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    dest: $HOME/.ssh/id_ed25519
    mode: 0600
    content: "{{ ssh_private_key }}"

- name: Clone selfhosted-config git repository
  become_user: "{{ user.username }}"
  ansible.builtin.git:
    repo: git@github.com:jj-style/selfhosted-config.git
    dest: $HOME/selfhosted-config
    clone: yes
    update: yes
    accept_hostkey: true

