- name: Template samba config
  ansible.builtin.template:
    src: etc_samba_smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"

# https://stackoverflow.com/a/46428282
- name: Configure Samba users.
  shell: >
    (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -s -a {{ item.username }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  notify: Restart Samba
  with_items: "{{ samba_users }}"
  loop_control:
    label: "{{ item.username }}"
