- name: ufw allow ssh
  tags: firewall
  ufw:
    rule: limit
    app: openssh

- name: ufw allow Samba
  tags: firewall
  ufw:
    rule: allow
    app: samba

- name: ufw allow all access from speicifed IP addresses
  tags: firewall
  ufw:
    rule: allow
    src: "{{ item }}"
  loop: "{{ ufw_allowed_ips }}"

- name: ufw allow tailscale traffic
  tags: firewall
  ufw:
    rule: allow
    direction: in
    interface: tailscale0

- name: enable ufw
  tags: firewall
  ufw:
    state: enabled
    policy: deny
    logging: on
