---
- hosts: wilson
  become: true
  roles:
    - role: grog.package
      apply:
        tags: packages
      tags: packages
    - role: ironicbadger.bash_aliases
      apply:
        tags: bash_aliases
      tags: bash_aliases
    - role: flatpak
      apply:
        tags: flatpak
      tags: flatpak
    - base
    
    - role: geerlingguy.docker
    
    - role: wireguard
      apply:
        tags: vpn,wireguard
      tags: vpn,wireguard

    - role: artis3n.tailscale
      apply:
        tags: vpn,tailscale
      tags: vpn,tailscale
    
    - chezmoi
    - nas
    - role: diun
      apply:
        tags: diun
      tags: diun
  vars_files:
    - "../vars/vault.yml"
