---

- name: install wireguard package
  package:
    name: wireguard
    state: latest
    update_cache: yes

- name: create server wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: server_wg0.conf.j2
    owner: root
    group: root
    mode: '0600'
  notify: Restart Wireguard

- name: enable and persist ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes

- name: start wireguard and enable on boot
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

- name: enable wireguard watchdog
  template:
    dest: /usr/local/bin/wg-watchdog.sh
    src: watchdog.sh.j2
    owner: root
    group: root
    mode: '0600'
  when:  wireguard.watchdog.enabled|default(false)|bool

- name: create cronjob for wireguard watchdog
  ansible.builtin.cron:
    user: root
    name: "wireguard-watchdog"
    backup: true
    state: present
    cron_file: wg-watchdog
    minute: "*/1"
    job: "bash /usr/local/bin/wg-watchdog.sh"
  when: wireguard.watchdog.enabled|default(false)|bool
